### ISSUE TITLE
ModuleNotFoundError: No module named 'local_settings'

### ISSUE THREAD

**Issue by Omeiza17** [AndyRae/semita#12]
Hello
I am interested in your project and trying to run it on my local machine but I am getting the following error. Could you help me out, please?
`from local_settings import S_KEY
ModuleNotFoundError: No module named 'local_settings'`

**Comment by AndyRae** [comment]
Hey - thanks for your interest! You'll find it a simple project so far. 

But essentially we're importing the Secret Key Django uses in the settings.py, from a local_settings.py file. I've added a quick example file into the repo - local_settings_example, if you just rename this it will work.

Andy
